[package]
name = "oscr-core"
version = "0.1.0"
edition = "2021"
license.workspace = true
description = "Minimal-dependency, `no_std` friendly Open Sound Control (OSC) library"
repository = "https://jump.codeberg.page/oscr"

[features]
default = ["std", "parse", "serialize", "compat", "lut"]
std = ["alloc"]
alloc = []
parse = []
serialize = []
pattern = []
match = ["pattern"]
compat = ["compat_immediate_zero", "compat_optional_tag_string", "compat_trailing_slash"]
compat_immediate_zero = []
compat_optional_tag_string = []
compat_trailing_slash = []
lut = ["lut_tag", "lut_address_check", "lut_pattern_charset"]
lut_tag = []
lut_address_check = []
lut_pattern_charset = []
